[package]
name = "pomotui"
authors = ["Lasse Edslev <lasse2905@gmail.com>"]
repository = "https://github.com/LWEdslev/pomotui"
description = "A simple pomodoro timer with a flexible TUI"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
tui = "0.19.0"
